language: ruby
script:
- rake --trace
- ls -lR
deploy:
  skip_cleanup: true
  provider: rubygems
  file_glob: true
  file: pkg/*.gem
  on:
    tags: false
    all_branches: true
branches:
  only:
  - master
  - /^release.*/
env:
  global:
  #GIT_TAG_PUSHER
    - secure: YcGPIUFRX8N1xp835zo2RWMmBQXxrVrsqx7vFK8iAhdYYKO0tc2sAYjjxrDuWy7gAbhyW1dnm3I6wQKluNIhmHCFY486BlGR6hwVgNy7eRtmMqGJ2E8be1+sxe2di09H6h/s1+PNqx+snWU/WK5tFVx9PCZmDfeYNJlWgoCU4jAEV+7Wo240aUtbxv6++QSzr3mUMCh3YSTtUqMzScmP7GBTQZVejF2+tB2taGH2rcmc5SCovT3t5eZqoeosgNNHVYQYRsS92ScANX00KxxVzMl61uHKOUS4hvNTB2e9FfFVIjIfZIImjNJ6BMHFVfP6l2TRu3ajlZpTHX/Y8sdUnfgzrc6qniFDAkUNxgKaj3+LUKMABIjxfMxbk7Mp/qyGftj7iGG+7WJuHntu3KJn8afQgwcOvc8Go2pr/xVYNPQskgooUtup9kFkZpiT5xwe4AzyKcUwkwzntlNGLvSlGZuQLeDljtuxEECobblZfAVv5mPWjZYKFYuueouXG9YjqtgV2Tmsdx1FIWRs/ADvowL1OiiszRakoRo/bdN/N8vmSFYUDCrSQl/RwoFZ/jklwZ3ayMQSI4E5YGpSDYdjJPvJCPzv38OtuWN8C+FLHwG73zlXf+fMNnqOCN6UT5CPj2RUWpzPBjmqTugU+/3V8HxyclDuSWy36jFAwDzgxGE=
